#highlighter: pygments
highlighter: rouge
destination: /tmp/_site
url: https://blog.aibor.de
excerpt_separator: ""
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      monthnames: [Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember]
